/*
  Personas Database — v1
  ---------------------------------
  Purpose: Provide a comprehensive, hand‑curated set of personas for Prompt Builder / Persona Builder.
  Format: Plain JS that attaches PERSONAS to window (browser) and module.exports (Node/CommonJS) for flexibility.

  Minimal schema used by v1 UI (others can be tucked under `meta` and ignored by v1):

  {
    id: string,                  // slug/id used for lookups (kebab-case)
    name: string,                // human label (shown in the picker)
    profession: string,          // broad profession or discipline
    summary: string,             // 1–2 lines summary
    description?: string,        // optional, longer narrative
    core_tasks: string[],        // 3–8 short task verbs/phrases
    skills: string[],            // core abilities/competencies
    vocabulary: string[],        // domain terms/jargon (stingy + precise)
    goals: string[],             // common success targets
    pain_points: string[],       // recurring blockers/frictions
    tools: string[],             // common tools/platforms
    tags: string[],              // key:value chips to power typeahead & filters
    mappings: {                  // external taxonomies (optional)
      esco_occupation?: string,
      onetsoc?: string,
      iscocode?: string
    },
    meta?: {                     // ignored by v1; free real-estate for later
      seniority?: string[],      // e.g., ["junior","mid","senior","lead"]
      industries?: string[],
      synonyms?: string[]        // extra search hooks
    }
  }
*/

;(function(root){
  const PERSONAS = [
    // ===== Design & Research =====
    {
      id: "ux-designer",
      name: "UX designer",
      profession: "Designer",
      summary: "Designs intuitive, usable product experiences through flows, wireframes, and iterative testing.",
      core_tasks: [
        "Map user journeys and flows",
        "Wireframe and prototype key screens",
        "Plan and run usability tests",
        "Partner with PM/Eng on scope and trade‑offs"
      ],
      skills: ["Wireframing","Prototyping","Information architecture","Interaction design","Heuristic evaluation"],
      vocabulary: ["affordance","heuristics","flows","personas","Fitts' Law"],
      goals: ["Improve task success","Reduce friction","Increase adoption"],
      pain_points: ["Stakeholder misalignment","Rushed timelines","Legacy systems"],
      tools: ["Figma","FigJam","Axure","Maze","Lookback"],
      tags: ["discipline:design","domain:product","alias:ux","occupation:designer"],
      mappings: { esco_occupation: "", onetsoc: "" }
    },
    {
      id: "ux-researcher",
      name: "UX researcher",
      profession: "Researcher",
      summary: "Generates evidence about user needs and behavior to de‑risk product decisions.",
      core_tasks: ["Plan studies","Interview/observe users","Synthesize insights","Advise product decisions"],
      skills: ["Study design","Interviewing","Survey design","Thematic analysis","Triangulation"],
      vocabulary: ["moderated","unmoderated","SUS","JTBD","saturation"],
      goals: ["Surface actionable insights","Reduce decision risk","Represent user needs"],
      pain_points: ["Recruiting constraints","Low signal data","Last‑minute scope changes"],
      tools: ["UserTesting","Lookback","dscout","Qualtrics","NVivo"],
      tags: ["discipline:research","domain:product","alias:uxr","occupation:researcher"],
      mappings: {}
    },
    {
      id: "product-designer",
      name: "Product designer",
      profession: "Designer",
      summary: "Owns end‑to‑end product UX from discovery to polished UI across surfaces.",
      core_tasks: ["Discovery workshops","Flow + IA","Hi‑fi UI","Design QA"],
      skills: ["Systems thinking","Design tokens","Prototyping","Accessibility","Design critique"],
      vocabulary: ["component library","tokens","nudge","empty state","progressive disclosure"],
      goals: ["Shippable clarity","Consistency","Accessibility"],
      pain_points: ["Fragmented design systems","Ad‑hoc requests","Engineering drift"],
      tools: ["Figma","Storybook","Zeplin"],
      tags: ["discipline:design","domain:product","alias:pd"],
      mappings: {}
    },
    {
      id: "ui-designer",
      name: "UI designer",
      profession: "Designer",
      summary: "Crafts visual systems, layouts, and components for crisp, legible interfaces.",
      core_tasks: ["Design component library","Visual polish","Spec spacing/typography","Create assets"],
      skills: ["Visual hierarchy","Color systems","Grid/layout","Iconography","Design tokens"],
      vocabulary: ["8‑pt grid","contrast ratio","leading","kerning","elevation"],
      goals: ["Legibility","Consistency","Brand alignment"],
      pain_points: ["Token drift","Non‑semantic CSS","Asset duplication"],
      tools: ["Figma","Adobe Illustrator","Lottie"],
      tags: ["discipline:design","domain:ui","alias:visual-designer"],
      mappings: {}
    },
    {
      id: "content-designer",
      name: "Content designer / UX writer",
      profession: "Writer",
      summary: "Designs product language, information, and microcopy to guide users to success.",
      core_tasks: ["Audit content and flows","Draft microcopy","Establish voice & tone","Partner on IA"],
      skills: ["Plain language","Voice & tone","Content modeling","Localization","Acceptance criteria"],
      vocabulary: ["microcopy","voice & tone","terminology","string table","empty state"],
      goals: ["Clarity","Task completion","Consistency"],
      pain_points: ["Late involvement","String sprawl","Unclear source of truth"],
      tools: ["Figma","Google Docs","Phrase","Smartling"],
      tags: ["discipline:content","domain:product","alias:ux-writer"],
      mappings: {}
    },
    {
      id: "service-designer",
      name: "Service designer",
      profession: "Designer",
      summary: "Designs end‑to‑end service experiences across channels, actors, and backstage systems.",
      core_tasks: ["Map ecosystems","Blueprint services","Identify failure points","Pilot improvements"],
      skills: ["Journey mapping","Service blueprinting","Stakeholder facilitation","Systems mapping"],
      vocabulary: ["frontstage","backstage","touchpoint","evidence","handoff"],
      goals: ["Seamless journeys","Operational feasibility","Measurable outcomes"],
      pain_points: ["Siloed ownership","Legacy processes","Data fragmentation"],
      tools: ["Miro","Figma","Lucidchart"],
      tags: ["discipline:design","domain:service","method:blueprint"],
      mappings: {}
    },

    // ===== Product & Delivery =====
    {
      id: "product-manager",
      name: "Product manager",
      profession: "PM",
      summary: "Aligns customer value and business impact through discovery, prioritization, and delivery.",
      core_tasks: ["Define problems & outcomes","Prioritize roadmap","Write specs/PRDs","Partner with Eng/Design"],
      skills: ["Prioritization","Stakeholder management","Data literacy","Experiment design","Narrative writing"],
      vocabulary: ["PRD","MVP","OKR","RICE","north star"],
      goals: ["Ship impact","Customer satisfaction","Learning velocity"],
      pain_points: ["Competing priorities","Ambiguity","Hidden dependencies"],
      tools: ["Jira","Productboard","Amplitude","Looker"],
      tags: ["discipline:product","domain:software","alias:pm"],
      mappings: {}
    },
    {
      id: "technical-product-manager",
      name: "Technical product manager",
      profession: "PM",
      summary: "Owns platform/API/infra products; balances developer experience with scalability and risk.",
      core_tasks: ["API/product strategy","Backlog refinement","Write technical specs","Rollout/metrics"],
      skills: ["Systems thinking","API design basics","Program management","Risk assessment"],
      vocabulary: ["SLAs","SDK","idempotency","rate limiting","backward compatibility"],
      goals: ["Reliable platforms","DX satisfaction","Adoption by internal teams"],
      pain_points: ["Non‑functional requirements","Legacy contracts","Resource contention"],
      tools: ["Swagger/OpenAPI","Postman","Jira","Grafana"],
      tags: ["discipline:product","domain:platform","alias:tpm"],
      mappings: {}
    },
    {
      id: "program-manager",
      name: "Program manager",
      profession: "Program management",
      summary: "Coordinates multi‑team initiatives to land outcomes on predictable schedules.",
      core_tasks: ["Plan milestones","Own cross‑team risks","Run status cadences","Drive decisions"],
      skills: ["Dependency mapping","Risk management","Communication","Change management"],
      vocabulary: ["RFC","RACI","critical path","status cadence","health metrics"],
      goals: ["Predictable delivery","Unblocked teams","Clear accountability"],
      pain_points: ["Shifting scope","Hidden blockers","Decision latency"],
      tools: ["Jira","Asana","Confluence","Smartsheet"],
      tags: ["discipline:program","domain:delivery"],
      mappings: {}
    },
    {
      id: "project-manager",
      name: "Project manager",
      profession: "Project management",
      summary: "Plans, executes, and closes projects with scope, schedule, and budget under control.",
      core_tasks: ["Plan WBS & schedule","Budget & resources","Track execution","Stakeholder updates"],
      skills: ["Scheduling","Budgeting","Risk/issue tracking","Vendor management"],
      vocabulary: ["WBS","critical path","baseline","scope creep","EAC"],
      goals: ["On‑time, on‑budget","Scope adherence","Stakeholder satisfaction"],
      pain_points: ["Unclear scope","Resource constraints","Late requirement changes"],
      tools: ["MS Project","Asana","Jira","Smartsheet"],
      tags: ["discipline:project","domain:delivery"],
      mappings: {}
    },
    {
      id: "scrum-master",
      name: "Scrum master",
      profession: "Agile coach",
      summary: "Facilitates Scrum, removes impediments, and improves team flow and practices.",
      core_tasks: ["Coach Scrum events","Remove impediments","Track flow metrics","Foster continuous improvement"],
      skills: ["Facilitation","Coaching","Kanban/Scrum","Conflict resolution"],
      vocabulary: ["velocity","WIP","retrospective","definition of done","story points"],
      goals: ["Predictable delivery","Healthy team","Continuous improvement"],
      pain_points: ["Cargo‑cult Scrum","Over‑commitment","Cross‑team blockers"],
      tools: ["Jira","Miro","Azure Boards"],
      tags: ["discipline:agile","domain:delivery"],
      mappings: {}
    },

    // ===== Engineering =====
    {
      id: "frontend-engineer",
      name: "Frontend engineer",
      profession: "Engineer",
      summary: "Builds accessible, performant web/mobile UIs with modern frameworks.",
      core_tasks: ["Implement UI components","State management","Accessibility fixes","Perf optimizations"],
      skills: ["JavaScript/TypeScript","React/Vue","Accessibility (WCAG)","Testing (Jest/RTL)","CSS architectures"],
      vocabulary: ["hydration","ARIA","bundle splitting","CLS","CSR/SSR"],
      goals: ["Fast, accessible UIs","Maintainable code","Low regressions"],
      pain_points: ["Design drift","Flaky tests","CSS specificity wars"],
      tools: ["VS Code","React","Vite","Storybook","Playwright"],
      tags: ["discipline:engineering","domain:web","alias:fe"],
      mappings: { onetsoc: "15-1254.00" }
    },
    {
      id: "backend-engineer",
      name: "Backend engineer",
      profession: "Engineer",
      summary: "Designs and maintains server systems, APIs, and data stores for reliability and scale.",
      core_tasks: ["Design APIs","Model data","Implement business logic","Operate services"],
      skills: ["Distributed systems","Databases","Concurrency","Observability","Security basics"],
      vocabulary: ["idempotency","consistency","throughput","SLO/SLA/SLA","backpressure"],
      goals: ["Reliable services","Clear contracts","Cost‑efficient scale"],
      pain_points: ["Hidden coupling","Slow queries","Pager fatigue"],
      tools: ["PostgreSQL","Redis","gRPC","Docker","Kubernetes"],
      tags: ["discipline:engineering","domain:backend"],
      mappings: { onetsoc: "15-1252.00" }
    },
    {
      id: "fullstack-engineer",
      name: "Full‑stack engineer",
      profession: "Engineer",
      summary: "Delivers features across UI, API, and data with pragmatic end‑to‑end ownership.",
      core_tasks: ["Ship vertical slices","Own PRs/E2E tests","Debug across layers","Shepherd releases"],
      skills: ["React","Node/Java","SQL","Testing","CI/CD"],
      vocabulary: ["feature flag","blue/green","migration","contract tests","trunk‑based"],
      goals: ["Customer impact","Quality","Sustainable pace"],
      pain_points: ["Context switching","Env parity issues","Ambiguous ownership"],
      tools: ["GitHub","Postman","Datadog","Docker"],
      tags: ["discipline:engineering","domain:product","alias:fs"],
      mappings: {}
    },
    {
      id: "mobile-engineer",
      name: "Mobile engineer",
      profession: "Engineer",
      summary: "Builds native or cross‑platform mobile apps with smooth UX and efficient resource use.",
      core_tasks: ["Implement screens","Handle lifecycle/push","Optimize performance","Ship to stores"],
      skills: ["Swift/Kotlin or React Native","Offline sync","Threading","Instrumentation"],
      vocabulary: ["ANR","App Store review","deeplink","ViewModel","RecyclerView"],
      goals: ["Stable releases","Smooth UX","Good ratings"],
      pain_points: ["Store review delays","Device fragmentation","Crash debugging"],
      tools: ["Xcode","Android Studio","Firebase","Fastlane"],
      tags: ["discipline:engineering","domain:mobile"],
      mappings: {}
    },
    {
      id: "devops-engineer",
      name: "DevOps engineer",
      profession: "Engineer",
      summary: "Automates delivery pipelines, infrastructure, and observability for fast, safe deploys.",
      core_tasks: ["CI/CD pipelines","Infra as code","Monitoring/alerts","Cost optimization"],
      skills: ["Cloud (AWS/GCP/Azure)","Terraform","Linux","Networking","SRE practices"],
      vocabulary: ["immutable infra","runbook","canary","IaC","toil"],
      goals: ["High deployment frequency","Low change failure","Fast MTTR"],
      pain_points: ["Snowflake servers","Poor incident hygiene","Secret sprawl"],
      tools: ["Terraform","GitHub Actions","ArgoCD","Prometheus","Grafana"],
      tags: ["discipline:engineering","domain:platform","alias:platform-engineer"],
      mappings: {}
    },
    {
      id: "site-reliability-engineer",
      name: "Site reliability engineer (SRE)",
      profession: "Engineer",
      summary: "Improves reliability through SLOs, automation, and incident response.",
      core_tasks: ["Define SLOs/SLIs","Reduce toil","Run incident reviews","Capacity planning"],
      skills: ["Observability","Automation","Incident response","Performance analysis"],
      vocabulary: ["error budget","SLO","blameless postmortem","MTTR","SLA"],
      goals: ["Uptime within budgets","Predictable performance","Learning from incidents"],
      pain_points: ["Alert noise","Hero culture","Unowned reliability work"],
      tools: ["PagerDuty","Datadog","Sentry","Grafana"],
      tags: ["discipline:engineering","domain:reliability","alias:sre"],
      mappings: {}
    },
    {
      id: "qa-engineer",
      name: "QA engineer / Test automation",
      profession: "Quality",
      summary: "Prevents regressions via risk‑based testing, automation, and clear acceptance criteria.",
      core_tasks: ["Define test strategy","Automate critical paths","Exploratory testing","Track defects"],
      skills: ["Test design","Automation frameworks","CI integration","Risk analysis"],
      vocabulary: ["flaky","coverage","smoke test","regression","test pyramid"],
      goals: ["Catch issues early","Stable releases","Fast feedback"],
      pain_points: ["Brittle UI tests","Env drift","Late testability"],
      tools: ["Playwright","Cypress","Selenium","Postman"],
      tags: ["discipline:quality","domain:testing"],
      mappings: {}
    },
    {
      id: "security-engineer",
      name: "Security engineer",
      profession: "Engineer",
      summary: "Reduces security risk with prevention, detection, and secure‑by‑default patterns.",
      core_tasks: ["Threat modeling","Code review/SDLC","Vuln management","Incident response"],
      skills: ["AppSec","Cloud security","IAM","Threat detection","Secure coding"],
      vocabulary: ["OWASP","least privilege","CSP","CVE","secrets management"],
      goals: ["Fewer exploitable vulns","Developer enablement","Compliance posture"],
      pain_points: ["Late engagement","Shadow IT","Tool sprawl"],
      tools: ["Burp Suite","Zap","Snyk","Falco","CrowdStrike"],
      tags: ["discipline:security","domain:appsec"],
      mappings: {}
    },
    {
      id: "solutions-architect",
      name: "Solutions architect",
      profession: "Architecture",
      summary: "Designs end‑to‑end solutions that meet requirements, constraints, and non‑functionals.",
      core_tasks: ["Elicit requirements","Design architecture","Evaluate build vs buy","Guide implementation"],
      skills: ["Systems modeling","Costing","Risk trade‑offs","Vendor evaluation"],
      vocabulary: ["non‑functional","latency budget","availability","integration pattern","SaaS vs PaaS"],
      goals: ["Right‑sized design","Future extensibility","Operational fit"],
      pain_points: ["Hidden constraints","Vendor lock‑in","Shifting scope"],
      tools: ["C4 diagrams","Draw.io","Cloud Well‑Architected"],
      tags: ["discipline:architecture","domain:enterprise"],
      mappings: {}
    },

    // ===== Data =====
    {
      id: "data-analyst",
      name: "Data analyst",
      profession: "Analyst",
      summary: "Answers decision questions with clean datasets, clear visuals, and crisp narratives.",
      core_tasks: ["Define KPIs","Build queries & dashboards","Analyze trends","Communicate insights"],
      skills: ["SQL","Spreadsheets","Dashboarding","A/B analysis","Data cleaning"],
      vocabulary: ["cohort","funnel","lift","confidence interval","segment"],
      goals: ["Decision clarity","Reliable KPIs","Self‑serve data"],
      pain_points: ["Messy sources","Metric drift","Ad‑hoc fire drills"],
      tools: ["BigQuery","Snowflake","Looker","Tableau"],
      tags: ["discipline:data","domain:analytics"],
      mappings: {}
    },
    {
      id: "data-scientist",
      name: "Data scientist",
      profession: "Scientist",
      summary: "Builds models and analyses to predict, explain, or optimize outcomes.",
      core_tasks: ["Frame problems","Feature engineering","Train/evaluate models","Explain impacts"],
      skills: ["Statistics","ML","Python/R","Experimentation","Causal inference"],
      vocabulary: ["overfitting","AUC","uplift","regularization","leakage"],
      goals: ["Model quality","Business impact","Reproducibility"],
      pain_points: ["Data leakage","Shift in production","Unclear success metrics"],
      tools: ["Python","Pandas","Scikit‑learn","Jupyter","MLflow"],
      tags: ["discipline:data","domain:ml"],
      mappings: {}
    },
    {
      id: "data-engineer",
      name: "Data engineer",
      profession: "Engineer",
      summary: "Builds reliable data pipelines and warehouses for analytics and ML.",
      core_tasks: ["Ingest/transform data","Model warehouses","Manage orchestration","Ensure quality"],
      skills: ["ETL/ELT","SQL modeling","Orchestration","Data quality","Cloud storage"],
      vocabulary: ["CDC","star schema","delta lake","idempotent loads","lineage"],
      goals: ["Fresh, accurate data","Scalable pipelines","Low cost"],
      pain_points: ["Schema drift","Late arriving data","Backfills"],
      tools: ["dbt","Airflow","Spark","BigQuery/Snowflake"],
      tags: ["discipline:data","domain:platform"],
      mappings: {}
    },
    {
      id: "analytics-engineer",
      name: "Analytics engineer",
      profession: "Engineer",
      summary: "Bridges data engineering and analysis to model business‑ready datasets.",
      core_tasks: ["Model marts","Define metrics","Review PRs","Enable self‑serve"],
      skills: ["dbt","SQL","Version control","Documentation","Testing"],
      vocabulary: ["semantic layer","source freshness","data tests","metrics store","SLAs"],
      goals: ["Trustworthy metrics","Clear models","Analyst velocity"],
      pain_points: ["Metric disputes","Orphaned tables","Untracked changes"],
      tools: ["dbt","LookML","GitHub","Great Expectations"],
      tags: ["discipline:data","domain:analytics"],
      mappings: {}
    },
    {
      id: "statistician",
      name: "Statistician",
      profession: "Statistician",
      summary: "Designs studies and applies statistical methods to extract valid conclusions.",
      core_tasks: ["Study design","Sampling & power","Fit models","Interpret results"],
      skills: ["Experimental design","Regression","Bayesian methods","Diagnostics"],
      vocabulary: ["p‑value","power","posterior","heteroscedasticity","confounding"],
      goals: ["Validity","Precision","Transparency"],
      pain_points: ["P‑hacking pressure","Underpowered studies","Bad data"],
      tools: ["R","Stan","Python","JMP"],
      tags: ["discipline:data","domain:statistics"],
      mappings: {}
    },

    // ===== Marketing =====
    {
      id: "product-marketing-manager",
      name: "Product marketing manager",
      profession: "Marketing",
      summary: "Positions products, launches features, and equips sales with crisp narratives.",
      core_tasks: ["Messaging & positioning","Launch planning","Enable sales","Market research"],
      skills: ["Narrative building","Segmentation","Competitive analysis","Go‑to‑market"],
      vocabulary: ["ICP","value prop","battlecards","launch tier","category"],
      goals: ["Adoption","Pipeline","Differentiation"],
      pain_points: ["Crowded markets","Late alignment","Content bottlenecks"],
      tools: ["Google Slides","HubSpot","Airtable","Gong"],
      tags: ["discipline:marketing","domain:product"],
      mappings: {}
    },
    {
      id: "growth-marketer",
      name: "Growth marketer",
      profession: "Marketing",
      summary: "Runs experiments across the funnel to acquire, activate, and retain users.",
      core_tasks: ["Form hypotheses","Run A/B tests","Optimize channels","Analyze cohorts"],
      skills: ["Experiment design","Lifecycle marketing","Attribution","SQL basics"],
      vocabulary: ["CAC","LTV","north star","activation","retention"],
      goals: ["Efficient growth","Learning velocity","Sustainable loops"],
      pain_points: ["Attribution murkiness","Low sample sizes","Channel fatigue"],
      tools: ["GA4","Amplitude","Optimizely","Braze"],
      tags: ["discipline:marketing","domain:growth"],
      mappings: {}
    },
    {
      id: "content-marketer",
      name: "Content marketer",
      profession: "Marketing",
      summary: "Creates educational content that builds trust and drives demand.",
      core_tasks: ["Editorial calendar","SEO briefs","Draft/edit","Repurpose content"],
      skills: ["Storytelling","SEO basics","Interviewing SMEs","CMS"],
      vocabulary: ["pillar/cluster","SERP intent","CTAs","backlinks","UTM"],
      goals: ["Qualified traffic","Engagement","Leads"],
      pain_points: ["Thin content requests","SME availability","Distribution gaps"],
      tools: ["CMS","Ahrefs","Grammarly","Canva"],
      tags: ["discipline:marketing","domain:content"],
      mappings: {}
    },
    {
      id: "seo-specialist",
      name: "SEO specialist",
      profession: "Marketing",
      summary: "Improves organic visibility through technical fixes, content, and authority building.",
      core_tasks: ["Technical audits","Keyword research","On‑page fixes","Link strategy"],
      skills: ["Crawling/indexing","Schema markup","Analytics","Content briefs"],
      vocabulary: ["canonical","crawl budget","E‑E‑A‑T","structured data","Core Web Vitals"],
      goals: ["Non‑brand growth","Share of voice","Healthy technical baseline"],
      pain_points: ["Dev backlog","Legacy CMS","Algorithm shifts"],
      tools: ["Search Console","Screaming Frog","Ahrefs","GA4"],
      tags: ["discipline:marketing","domain:seo"],
      mappings: {}
    },
    {
      id: "social-media-manager",
      name: "Social media manager",
      profession: "Marketing",
      summary: "Builds brand presence and community across social platforms.",
      core_tasks: ["Content calendar","Engage community","Measure performance","Manage creators"],
      skills: ["Copy & visuals","Community management","Analytics","Crisis handling"],
      vocabulary: ["reach","engagement rate","creator economy","trendjacking","UGC"],
      goals: ["Brand awareness","Engagement","Community health"],
      pain_points: ["Algorithm changes","Approval bottlenecks","Comment moderation"],
      tools: ["Hootsuite","Sprout Social","Canva","CapCut"],
      tags: ["discipline:marketing","domain:social"],
      mappings: {}
    },

    // ===== Sales, Success, Support =====
    {
      id: "account-executive",
      name: "Account executive",
      profession: "Sales",
      summary: "Closes deals by diagnosing needs, demoing value, and navigating procurement.",
      core_tasks: ["Discovery & qualification","Demo & ROI","Proposal & negotiation","Forecast & updates"],
      skills: ["Discovery","Objection handling","Relationship building","Deal strategy"],
      vocabulary: ["MEDDICC","POC","land and expand","mutual close plan","stakeholder map"],
      goals: ["Quota attainment","Win rate","Sales cycle time"],
      pain_points: ["Stalled champions","Procurement friction","Competitive FUD"],
      tools: ["Salesforce","Gong","Chili Piper"],
      tags: ["discipline:sales","domain:b2b"],
      mappings: {}
    },
    {
      id: "sales-development-rep",
      name: "Sales development rep (SDR)",
      profession: "Sales",
      summary: "Creates pipeline by prospecting, qualifying, and booking meetings.",
      core_tasks: ["Prospect & research","Outbound sequences","Qualify leads","Handoff to AE"],
      skills: ["Cold outreach","Messaging","Time management","CRM hygiene"],
      vocabulary: ["ICP","sequence","meeting set","connect rate","oppty"],
      goals: ["Meetings set","Pipeline created","Response rates"],
      pain_points: ["List quality","Spam filters","Message fatigue"],
      tools: ["Salesloft","Outreach","LinkedIn Sales Navigator"],
      tags: ["discipline:sales","domain:prospecting","alias:bdr"],
      mappings: {}
    },
    {
      id: "solutions-engineer",
      name: "Solutions engineer (SE)",
      profession: "Sales engineering",
      summary: "Partners with sales to design and validate technical solutions that win and retain customers.",
      core_tasks: ["Discovery & scoping","Custom demos/POCs","Security & architecture Q&A","Handover to post‑sales"],
      skills: ["Pre‑sales discovery","Scripting","Systems integration","Objection handling"],
      vocabulary: ["RFP/RFI","POC","pilot","SOW","reference architecture"],
      goals: ["Technical win","Shorter cycles","Low implementation risk"],
      pain_points: ["Custom demo debt","Security questionnaires","Unclear fit"],
      tools: ["Postman","Docker","Demo environments","Notion"],
      tags: ["discipline:sales","domain:solutions"],
      mappings: {}
    },
    {
      id: "customer-success-manager",
      name: "Customer success manager",
      profession: "Customer success",
      summary: "Ensures customers achieve outcomes and renew/expand through adoption and advocacy.",
      core_tasks: ["Onboard & enable","Health monitoring","QBRs","Renewals & advocacy"],
      skills: ["Relationship management","Value realization","Playbooks","Data literacy"],
      vocabulary: ["health score","time to value","adoption","churn risk","EBR/QBR"],
      goals: ["Renewal rate","Expansion","Adoption"],
      pain_points: ["Low executive buy‑in","Resource gaps","Reactive fire‑drills"],
      tools: ["Gainsight","Zendesk","ChurnZero"],
      tags: ["discipline:success","domain:post-sales"],
      mappings: {}
    },
    {
      id: "support-specialist",
      name: "Support specialist",
      profession: "Support",
      summary: "Resolves customer issues quickly and documents durable fixes.",
      core_tasks: ["Triage & troubleshoot","Knowledge base updates","Escalate bugs","Close the loop"],
      skills: ["Diagnostics","Communication","De‑escalation","Documentation"],
      vocabulary: ["SLA","ticket","repro steps","workaround","known issue"],
      goals: ["Fast resolution","High CSAT","Accurate docs"],
      pain_points: ["Insufficient context","Tool hopping","Reopened tickets"],
      tools: ["Zendesk","Intercom","Jira","Confluence"],
      tags: ["discipline:support","domain:operations"],
      mappings: {}
    },

    // ===== Ops, People, Finance, Legal =====
    {
      id: "operations-manager",
      name: "Operations manager",
      profession: "Operations",
      summary: "Optimizes processes, SLAs, and handoffs to keep the business running smoothly.",
      core_tasks: ["Map processes","Define SLAs","Measure performance","Drive improvements"],
      skills: ["Process design","Change management","Excel/SQL basics","Vendor management"],
      vocabulary: ["SOP","SLA","throughput","cycle time","capacity"],
      goals: ["Efficiency","Predictability","Quality"],
      pain_points: ["Workarounds","Shadow processes","Legacy tools"],
      tools: ["Airtable","Asana","Tableau","Zapier"],
      tags: ["discipline:operations","domain:business"],
      mappings: {}
    },
    {
      id: "recruiter",
      name: "Recruiter / Talent acquisition",
      profession: "People",
      summary: "Sources and closes candidates while partnering with hiring managers on a fair process.",
      core_tasks: ["Source & outreach","Screen & schedule","Coordinate interviews","Offer & close"],
      skills: ["Sourcing","Assessment","Negotiation","Employer branding"],
      vocabulary: ["pipeline","onsite","scorecard","bar","time‑to‑fill"],
      goals: ["Time‑to‑hire","Candidate experience","Quality of hire"],
      pain_points: ["Scheduling complexity","Noisy signals","Offer stalls"],
      tools: ["Greenhouse","Lever","LinkedIn Recruiter","Gem"],
      tags: ["discipline:people","domain:talent"],
      mappings: {}
    },
    {
      id: "hr-business-partner",
      name: "HR business partner",
      profession: "People",
      summary: "Advises leaders on org design, performance, and people programs.",
      core_tasks: ["Workforce planning","Performance cycles","Coach managers","Policy & compliance"],
      skills: ["Employment law basics","Coaching","Org design","Change management"],
      vocabulary: ["comp bands","PIP","RIF","calibration","employee relations"],
      goals: ["Healthy org","Fair processes","Retention"],
      pain_points: ["Policy ambiguity","Undertrained managers","Ad‑hoc escalations"],
      tools: ["Workday","BambooHR","Lattice"],
      tags: ["discipline:people","domain:hr"],
      mappings: {}
    },
    {
      id: "finance-analyst",
      name: "Finance analyst",
      profession: "Finance",
      summary: "Builds budgets, forecasts, and analyses that guide business decisions.",
      core_tasks: ["Budget vs actuals","Forecasting","Scenario modeling","Board metrics"],
      skills: ["Excel modeling","Accounting basics","SQL","Visualization"],
      vocabulary: ["ARR","gross margin","runway","CAGR","variance"],
      goals: ["Accurate forecasts","Cost control","Clear insights"],
      pain_points: ["Dirty data","Last‑minute asks","Disconnected systems"],
      tools: ["Excel/Sheets","Adaptive","NetSuite","Looker"],
      tags: ["discipline:finance","domain:fp&a"],
      mappings: {}
    },
    {
      id: "accountant",
      name: "Accountant",
      profession: "Finance",
      summary: "Maintains accurate financial records and compliant reporting.",
      core_tasks: ["Month‑end close","AP/AR","Reconciliations","Audit support"],
      skills: ["GAAP","Tax basics","Attention to detail","Controls"],
      vocabulary: ["accrual","deferral","GL","aging","trial balance"],
      goals: ["Accurate books","Timely close","Compliance"],
      pain_points: ["Late docs","Manual entries","System mismatches"],
      tools: ["NetSuite","QuickBooks","BlackLine"],
      tags: ["discipline:finance","domain:accounting"],
      mappings: {}
    },
    {
      id: "legal-counsel",
      name: "Legal counsel",
      profession: "Legal",
      summary: "Manages risk and enables business through contracts, policy, and advice.",
      core_tasks: ["Draft/review contracts","Advise on regs","IP and privacy","Dispute resolution"],
      skills: ["Contracting","Issue spotting","Negotiation","Research"],
      vocabulary: ["indemnity","liability cap","DPA","SOW","governing law"],
      goals: ["Risk managed","Business enabled","Compliance"],
      pain_points: ["Redline ping‑pong","Ambiguous regs","Last‑minute escalations"],
      tools: ["DocuSign CLM","Ironclad","Practical Law"],
      tags: ["discipline:legal","domain:corporate"],
      mappings: {}
    },
    {
      id: "compliance-officer",
      name: "Compliance officer",
      profession: "Risk",
      summary: "Implements controls and audits to meet regulatory and policy obligations.",
      core_tasks: ["Define controls","Run audits","Remediate gaps","Train org"],
      skills: ["Frameworks (SOC2/ISO)","Risk assessment","Policy writing","Vendor risk"],
      vocabulary: ["control","evidence","finding","remediation","attestation"],
      goals: ["Clean audits","Risk reduction","Culture of compliance"],
      pain_points: ["Evidence wrangling","Changing scope","Tool sprawl"],
      tools: ["Drata","Vanta","OneTrust"],
      tags: ["discipline:risk","domain:compliance"],
      mappings: {}
    },

    // ===== IT =====
    {
      id: "it-support-specialist",
      name: "IT support specialist",
      profession: "IT",
      summary: "Keeps employees productive by resolving device, access, and app issues.",
      core_tasks: ["Triage tickets","Provision accounts","Image devices","Document fixes"],
      skills: ["Troubleshooting","Scripting basics","Customer service","Asset mgmt"],
      vocabulary: ["MDM","SSO","ticket SLA","least privilege","onboarding"],
      goals: ["Fast resolution","Happy employees","Secure baseline"],
      pain_points: ["Shadow IT","Hardware delays","Repeat issues"],
      tools: ["JAMF","Intune","Okta","Zendesk"],
      tags: ["discipline:it","domain:helpdesk"],
      mappings: {}
    },
    {
      id: "system-administrator",
      name: "System administrator",
      profession: "IT",
      summary: "Manages servers, directories, and core services with automation and security.",
      core_tasks: ["Patch & config","Backup & recovery","Access management","Monitor & respond"],
      skills: ["Linux/Windows","Scripting","Networking","IAM"],
      vocabulary: ["GPO","ACL","RBAC","snapshot","hardening"],
      goals: ["Stable systems","Good performance","Secure posture"],
      pain_points: ["Legacy systems","Manual changes","Config drift"],
      tools: ["Ansible","PowerShell","vSphere","Zabbix"],
      tags: ["discipline:it","domain:systems"],
      mappings: {}
    },
    {
      id: "network-engineer",
      name: "Network engineer",
      profession: "IT",
      summary: "Designs and operates reliable, secure networks across sites and clouds.",
      core_tasks: ["Plan topology","Configure routers/switches","Troubleshoot","Capacity planning"],
      skills: ["Routing/switching","Firewalls/VPN","Wi‑Fi","Monitoring"],
      vocabulary: ["BGP","NAT","VLAN","QoS","Zero Trust"],
      goals: ["Availability","Throughput","Security"],
      pain_points: ["Incidents outside hours","Vendor quirks","Documentation debt"],
      tools: ["Cisco IOS","JunOS","NetBox","Wireshark"],
      tags: ["discipline:it","domain:networking"],
      mappings: {}
    },

    // ===== Education =====
    {
      id: "teacher",
      name: "Teacher",
      profession: "Educator",
      summary: "Designs learning experiences and manages classrooms to promote student growth.",
      core_tasks: ["Plan lessons","Differentiate instruction","Assess learning","Communicate with families"],
      skills: ["Curriculum design","Classroom management","Assessment","Ed‑tech"],
      vocabulary: ["scaffolding","formative assessment","IEP","standards","rubric"],
      goals: ["Student mastery","Equity","Engagement"],
      pain_points: ["Large class sizes","Limited prep time","Administrative load"],
      tools: ["Google Classroom","Canvas","Kahoot","Nearpod"],
      tags: ["discipline:education","domain:k12"],
      mappings: {}
    },
    {
      id: "instructional-designer",
      name: "Instructional designer",
      profession: "Educator",
      summary: "Builds courses and materials grounded in learning science and accessibility.",
      core_tasks: ["Analyze learner needs","Design objectives & assessments","Produce materials","Evaluate outcomes"],
      skills: ["ADDIE","Backwards design","Accessibility","Media production"],
      vocabulary: ["Bloom's taxonomy","learning objectives","rubrics","universal design","microlearning"],
      goals: ["Effective transfer","Inclusive design","Measurable outcomes"],
      pain_points: ["SME availability","Scope creep","Tool constraints"],
      tools: ["Articulate 360","Camtasia","LMS"],
      tags: ["discipline:education","domain:instructional-design"],
      mappings: {}
    },

    // ===== Healthcare =====
    {
      id: "physician",
      name: "Physician",
      profession: "Healthcare",
      summary: "Diagnoses and treats patients while coordinating interdisciplinary care.",
      core_tasks: ["History & exam","Order/interpret tests","Formulate plan","Document & communicate"],
      skills: ["Clinical reasoning","Risk/benefit","Communication","Evidence appraisal"],
      vocabulary: ["differential","contraindication","workup","prognosis","informed consent"],
      goals: ["Accurate diagnosis","Effective treatment","Patient safety"],
      pain_points: ["Time pressure","Prior auth","EHR friction"],
      tools: ["EHR","UpToDate","Dictation"],
      tags: ["discipline:healthcare","domain:clinical"],
      mappings: {}
    },
    {
      id: "nurse",
      name: "Nurse",
      profession: "Healthcare",
      summary: "Delivers patient care, education, and coordination across settings.",
      core_tasks: ["Assess & monitor","Administer meds","Educate patients","Coordinate care"],
      skills: ["Clinical skills","Prioritization","Documentation","Compassion"],
      vocabulary: ["care plan","vitals","triage","SBAR","scope of practice"],
      goals: ["Patient safety","Timely care","Patient understanding"],
      pain_points: ["Staffing levels","Alarm fatigue","Documentation burden"],
      tools: ["EHR","Medication admin systems","Monitors"],
      tags: ["discipline:healthcare","domain:nursing"],
      mappings: {}
    },

    // ===== Media & Creative =====
    {
      id: "journalist",
      name: "Journalist",
      profession: "Media",
      summary: "Reports facts with verification and clear storytelling under deadline.",
      core_tasks: ["Source & verify","Interview","Draft & edit","Publish with corrections policy"],
      skills: ["Research","AP style","Fact‑checking","Ethics"],
      vocabulary: ["lede","nut graf","on/off background","embargo","correction"],
      goals: ["Accuracy","Public interest","Clarity"],
      pain_points: ["Misinformation","Access limits","Time pressure"],
      tools: ["CMS","Transcription tools","FOIA portals"],
      tags: ["discipline:media","domain:news"],
      mappings: {}
    },
    {
      id: "video-producer",
      name: "Video producer",
      profession: "Media",
      summary: "Plans and delivers video content from pre‑production to post.",
      core_tasks: ["Write briefs/scripts","Plan shoots","Direct & capture","Edit & deliver"],
      skills: ["Shot planning","Lighting","Audio","Editing"],
      vocabulary: ["shot list","B‑roll","4:2:2","LUT","timeline"],
      goals: ["Compelling stories","On‑time delivery","Brand fit"],
      pain_points: ["Talent schedules","Rights/clearances","Hardware issues"],
      tools: ["Premiere Pro","DaVinci Resolve","After Effects"],
      tags: ["discipline:media","domain:video"],
      mappings: {}
    },
    
    {
      id: "graphic-designer",
      name: "Graphic designer",
      profession: "Designer",
      summary: "Creates visual communications for print and digital media.",
      core_tasks: ["Concept & moodboards","Layout & typography","Produce assets","Prep for print/web"],
      skills: ["Branding","Composition","Illustration","Pre‑press"],
      vocabulary: ["bleed","CMYK","grid","kerning","raster vs vector"],
      goals: ["Clear visuals","Brand consistency","Production‑ready assets"],
      pain_points: ["Vague briefs","Asset management","Last‑minute changes"],
      tools: ["Adobe Illustrator","Photoshop","InDesign","Figma"],
      tags: ["discipline:design","domain:graphic"],
      mappings: {}
    },
    
    // ===== Media & Creative (continued) =====
    {
      id: "art-director",
      name: "Art director",
      profession: "Creative",
      summary: "Leads visual concepts and art direction across campaigns and products.",
      core_tasks: ["Define visual concepts","Guide designers/illustrators","Review and critique","Partner with copy/production"],
      skills: ["Concepting","Composition","Typography","Direction","Feedback"],
      vocabulary: ["moodboard","storyboard","brand system","key visual","comps"],
      goals: ["Cohesive visuals","Brand consistency","High impact"],
      pain_points: ["Vague briefs","Last-minute pivots","Asset bottlenecks"],
      tools: ["Figma","Adobe Creative Cloud","Miro"],
      tags: ["discipline:design","domain:creative","role:lead"],
      mappings: {}
    },
    {
      id: "creative-director",
      name: "Creative director",
      profession: "Creative leadership",
      summary: "Owns overarching creative strategy and ensures ideas deliver business outcomes.",
      core_tasks: ["Set creative vision","Mentor teams","Pitch concepts","Align stakeholders"],
      skills: ["Narrative","Brand strategy","Presentation","Cross-functional leadership"],
      vocabulary: ["big idea","campaign platform","tone of voice","brand equity","guardrails"],
      goals: ["Memorable campaigns","Channel fit","Business lift"],
      pain_points: ["Consensus wrangling","Fragmented feedback","Budget constraints"],
      tools: ["Keynote/Slides","Figma","Asana"],
      tags: ["discipline:design","domain:brand","role:director"],
      mappings: {}
    },
    {
      id: "motion-designer",
      name: "Motion designer",
      profession: "Designer",
      summary: "Animates interfaces and graphics to clarify, delight, and guide attention.",
      core_tasks: ["Design motion specs","Animate UI/graphics","Render exports","Handoff to dev/video"],
      skills: ["Timing/easing","Layout","Compositing","Prototyping"],
      vocabulary: ["easing curve","anticipation","bezier","keyframes","render queue"],
      goals: ["Readable motion","Performance-friendly assets","Brand-coherent animation"],
      pain_points: ["Heavy files","Platform constraints","Last-minute script changes"],
      tools: ["After Effects","Lottie","Figma"],
      tags: ["discipline:design","domain:motion"],
      mappings: {}
    },
    {
      id: "3d-artist",
      name: "3D artist",
      profession: "Artist",
      summary: "Builds 3D models, materials, and renders for games, films, and product visuals.",
      core_tasks: ["Model assets","UV/unwrap & texture","Light & render","Optimize for engine"],
      skills: ["Modeling","Texturing","Lighting","Topology","Optimization"],
      vocabulary: ["PBR","UV map","normal map","retopo","bake"],
      goals: ["Believable materials","Optimized polycount","Consistent style"],
      pain_points: ["Tight render times","Asset rework","GPU limits"],
      tools: ["Blender","Maya","Substance 3D Painter","Unreal/Unity"],
      tags: ["discipline:3d","domain:media"],
      mappings: {}
    },
    {
      id: "illustrator",
      name: "Illustrator",
      profession: "Artist",
      summary: "Creates original illustrations and icons to communicate ideas and stories.",
      core_tasks: ["Sketch & iterate","Define style","Produce finals","Prep assets"],
      skills: ["Drawing","Composition","Color","Vector workflows"],
      vocabulary: ["line weight","flat vs depth","icon grid","glyph set","SVG"],
      goals: ["Distinctive style","Clarity at sizes","Asset consistency"],
      pain_points: ["Scope creep","Ambiguous style refs","Revision loops"],
      tools: ["Procreate","Adobe Illustrator","Figma"],
      tags: ["discipline:design","domain:illustration"],
      mappings: {}
    },
    {
      id: "advertising-copywriter",
      name: "Advertising copywriter",
      profession: "Copy",
      summary: "Writes headlines, body copy, and CTAs that persuade across channels.",
      core_tasks: ["Concept with art","Write variants","Test & refine","Ensure brand voice"],
      skills: ["Headlines","Benefits framing","CTA writing","Editing"],
      vocabulary: ["single-minded proposition","benefit ladder","CTA","tone","RTB"],
      goals: ["Clarity","Memorability","Conversion"],
      pain_points: ["Legal constraints","Short timelines","Too many approvers"],
      tools: ["Docs","Grammarly","Ad platforms"],
      tags: ["discipline:marketing","domain:advertising"],
      mappings: {}
    },
    {
      id: "brand-strategist",
      name: "Brand strategist",
      profession: "Strategy",
      summary: "Defines positioning, audience insight, and the narratives that connect them.",
      core_tasks: ["Research & segmentation","Craft positioning","Message map","Brief creative"],
      skills: ["Insight synthesis","Frameworks","Facilitation","Competitive analysis"],
      vocabulary: ["positioning","brand pillars","archetypes","ICP","proof points"],
      goals: ["Differentiation","Relevance","Consistency"],
      pain_points: ["Shifting priorities","Data gaps","Internal misalignment"],
      tools: ["Slides","Airtable","Qual/quant tools"],
      tags: ["discipline:brand","domain:strategy"],
      mappings: {}
    },
    {
      id: "public-relations-manager",
      name: "Public relations manager",
      profession: "PR",
      summary: "Builds relationships with media and manages announcements and issues.",
      core_tasks: ["Pitch stories","Manage press list","Prepare spokespeople","Crisis comms"],
      skills: ["Media relations","Writing","Crisis planning","Measurement"],
      vocabulary: ["embargo","exclusive","boilerplate","holding statement","tier-1"],
      goals: ["Coverage quality","Share of voice","Reputation"],
      pain_points: ["News cycles","Unclear messaging","Last-minute changes"],
      tools: ["Muck Rack","Cision","Press CMS"],
      tags: ["discipline:communications","domain:pr"],
      mappings: {}
    },
    {
      id: "email-marketer",
      name: "Email marketing specialist",
      profession: "Marketing",
      summary: "Designs lifecycle emails that inform, onboard, and convert.",
      core_tasks: ["Segment lists","Build templates","Write copy","A/B test & analyze"],
      skills: ["Lifecycle strategy","Deliverability","Copy","Automation"],
      vocabulary: ["open rate","CTR","ESP","UTM","suppression list"],
      goals: ["Engagement","Conversion","Retention"],
      pain_points: ["List hygiene","Template debt","Inconsistent data"],
      tools: ["Braze","Klaviyo","HubSpot"],
      tags: ["discipline:marketing","domain:email"],
      mappings: {}
    },
    {
      id: "paid-media-specialist",
      name: "Paid media specialist (PPC/SEM)",
      profession: "Marketing",
      summary: "Runs performance ad campaigns and optimizes spend across channels.",
      core_tasks: ["Keyword/audience research","Build campaigns","Tune bids/creatives","Report & learn"],
      skills: ["SEM/PPC","Attribution","Testing","Analytics"],
      vocabulary: ["ROAS","CPA","MTA","negative keywords","lookalike"],
      goals: ["Efficient spend","Qualified traffic","Scalable wins"],
      pain_points: ["Attribution noise","Creative fatigue","Policy rejections"],
      tools: ["Google Ads","Meta Ads","Looker"],
      tags: ["discipline:marketing","domain:performance"],
      mappings: {}
    },
    {
      id: "event-marketing-manager",
      name: "Event marketing manager",
      profession: "Marketing",
      summary: "Plans and executes events and field marketing to drive pipeline and brand.",
      core_tasks: ["Own calendar","Coordinate vendors","Promote & staff","Measure outcomes"],
      skills: ["Project management","Budgeting","Logistics","Experiential"],
      vocabulary: ["booth package","lead scan","sponsorship tier","run of show","follow-up SLA"],
      goals: ["Qualified leads","Positive ROI","Smooth execution"],
      pain_points: ["Venue constraints","Shipping hiccups","No-shows"],
      tools: ["Airtable","Splash","CRM"],
      tags: ["discipline:marketing","domain:events"],
      mappings: {}
    },
    {
      id: "podcast-producer",
      name: "Podcast producer",
      profession: "Media",
      summary: "Develops, records, and edits podcasts with consistent voice and quality.",
      core_tasks: ["Book guests","Prep run-downs","Record & edit","Publish & promote"],
      skills: ["Editorial","Audio editing","Project management","Interviewing"],
      vocabulary: ["room tone","non-destructive edit","compressor","RSS feed","ID3 tags"],
      goals: ["Compelling episodes","Audio quality","Audience growth"],
      pain_points: ["Scheduling","Room noise","Rights/clearances"],
      tools: ["Audition","Audacity","Descript","DAW"],
      tags: ["discipline:media","domain:audio"],
      mappings: {}
    },
    {
      id: "photographer",
      name: "Photographer",
      profession: "Media",
      summary: "Captures images that meet creative and technical requirements.",
      core_tasks: ["Plan shots","Light scenes","Capture & cull","Retouch & deliver"],
      skills: ["Lighting","Composition","Camera ops","Post-processing"],
      vocabulary: ["RAW","histogram","prime vs zoom","stops","color profile"],
      goals: ["Sharp, well-lit images","On-brief variety","Timely delivery"],
      pain_points: ["Weather/lighting","Client feedback loops","Gear failures"],
      tools: ["Lightroom","Photoshop","Cameras/Lenses"],
      tags: ["discipline:media","domain:photo"],
      mappings: {}
    },
    {
      id: "sound-designer",
      name: "Sound designer",
      profession: "Audio",
      summary: "Creates and integrates sound effects and ambiences for media and games.",
      core_tasks: ["Record/foley","Design SFX","Mix & master","Integrate with picture/engine"],
      skills: ["Recording","Synthesis","Mixing","Post workflows"],
      vocabulary: ["ADR","foley","limiter","stem","LFE"],
      goals: ["Clear dialog","Impactful SFX","Balanced mix"],
      pain_points: ["Noisy locations","Tight lock to picture","Format quirks"],
      tools: ["Pro Tools","Reaper","Wwise/FMOD"],
      tags: ["discipline:audio","domain:post"],
      mappings: {}
    },

    // ===== Game Development =====
    {
      id: "game-designer",
      name: "Game designer",
      profession: "Design",
      summary: "Designs mechanics, systems, and levels to deliver fun, fair gameplay.",
      core_tasks: ["Prototype mechanics","Tune balance","Write specs","Collaborate with art/eng"],
      skills: ["Systems thinking","Scripting","Playtesting","Economy design"],
      vocabulary: ["core loop","juice","telegraphing","metagame","balancing"],
      goals: ["Player engagement","Clarity","Replayability"],
      pain_points: ["Scope creep","Balancing grind","Tooling limits"],
      tools: ["Unity/Unreal","Miro","Spreadsheets"],
      tags: ["discipline:games","domain:design"],
      mappings: {}
    },
    {
      id: "game-developer",
      name: "Game developer (engine programmer)",
      profession: "Engineer",
      summary: "Implements gameplay and engine features with performance constraints.",
      core_tasks: ["Code gameplay systems","Profile & optimize","Integrate assets","Fix bugs"],
      skills: ["C#/C++","Rendering","Physics","Profiling"],
      vocabulary: ["draw calls","delta time","GC","navmesh","LOD"],
      goals: ["Stable FPS","Deterministic behavior","Low crashes"],
      pain_points: ["Asset churn","Platform certification","Merge conflicts"],
      tools: ["Unity/Unreal","Perforce/Git","Profilers"],
      tags: ["discipline:games","domain:engineering"],
      mappings: {}
    },
    {
      id: "narrative-designer",
      name: "Narrative designer",
      profession: "Writing",
      summary: "Crafts interactive narrative structures, dialogue, and lore.",
      core_tasks: ["Define narrative arcs","Write dialogue","Design branching","Collaborate on quests"],
      skills: ["Dialogue","Worldbuilding","Choice design","Tooling"],
      vocabulary: ["branching","barks","lore bible","beats","node graph"],
      goals: ["Emotional payoff","Player agency","Coherence"],
      pain_points: ["Tool limitations","Localization complexity","Continuity errors"],
      tools: ["Ink/Twine","Docs","Game editors"],
      tags: ["discipline:games","domain:narrative"],
      mappings: {}
    },

    // ===== Post-Sales / Delivery =====
    {
      id: "implementation-manager",
      name: "Implementation manager",
      profession: "Delivery",
      summary: "Leads customer onboarding and technical implementation to time-to-value.",
      core_tasks: ["Plan rollout","Configure/integrate","Train users","Handoff to CSM"],
      skills: ["Project management","Systems integration","Enablement","Comms"],
      vocabulary: ["SOW","runbook","cutover","sandbox","go-live"],
      goals: ["On-time launch","Adoption","Low risk"],
      pain_points: ["Unknown dependencies","Data mapping gaps","Resource contention"],
      tools: ["Asana","Postman","Confluence"],
      tags: ["discipline:services","domain:implementation"],
      mappings: {}
    },
    {
      id: "technical-account-manager",
      name: "Technical account manager (TAM)",
      profession: "Post-sales",
      summary: "Owns technical health of strategic accounts and coordinates solutions.",
      core_tasks: ["Run health reviews","Advise architecture","Escalation triage","Roadmap alignment"],
      skills: ["Systems thinking","Relationship mgmt","Prioritization","Presentation"],
      vocabulary: ["EBR","SLAs","risk register","workaround","RCAs"],
      goals: ["Account health","Renewals","Advocacy"],
      pain_points: ["Ambiguous ownership","Limited access","Competing priorities"],
      tools: ["Gainsight","Jira","Slides"],
      tags: ["discipline:success","domain:tam"],
      mappings: {}
    },
    {
      id: "onboarding-specialist",
      name: "Onboarding specialist",
      profession: "Services",
      summary: "Guides new customers through setup and early wins.",
      core_tasks: ["Set milestones","Configure basics","Train core users","Track adoption"],
      skills: ["Enablement","Documentation","Product expertise","Communication"],
      vocabulary: ["activation","time-to-value","nudge","cohort","stickiness"],
      goals: ["Fast activation","Confident users","Reduced churn risk"],
      pain_points: ["Low engagement","Data quality","Scheduling"],
      tools: ["Loom","Help Center","CRM"],
      tags: ["discipline:success","domain:onboarding"],
      mappings: {}
    },
    {
      id: "customer-support-manager",
      name: "Customer support manager",
      profession: "Support",
      summary: "Runs support operations and quality across channels.",
      core_tasks: ["Define SLAs","Coach agents","Improve KB","Report performance"],
      skills: ["Workforce mgmt","Process design","Quality assurance","Analytics"],
      vocabulary: ["first response","AHT","CSAT","deflection","KB"],
      goals: ["Fast, accurate answers","High CSAT","Lower reopen rate"],
      pain_points: ["Tool fragmentation","Knowledge gaps","Spike handling"],
      tools: ["Zendesk","Intercom","QA tools"],
      tags: ["discipline:support","domain:operations"],
      mappings: {}
    },

    // ===== Revenue Operations =====
    {
      id: "revops-analyst",
      name: "Revenue operations analyst",
      profession: "Operations",
      summary: "Improves revenue processes across marketing, sales, and success.",
      core_tasks: ["Map processes","Build dashboards","Diagnose leaks","Enable teams"],
      skills: ["CRM","SQL","Attribution","Change mgmt"],
      vocabulary: ["funnel","handoff SLA","ICP","lead scoring","forecast hygiene"],
      goals: ["Accurate pipeline","Smooth handoffs","Higher conversion"],
      pain_points: ["Dirty data","Shadow processes","Tool sprawl"],
      tools: ["Salesforce","HubSpot","Looker"],
      tags: ["discipline:operations","domain:revenue"],
      mappings: {}
    },
    {
      id: "sales-operations-manager",
      name: "Sales operations manager",
      profession: "Sales ops",
      summary: "Owns sales process, tooling, and forecasting cadence.",
      core_tasks: ["Forecast cadences","Territories/quotas","Process improvements","Admin tools"],
      skills: ["Process design","Modeling","Communication","CRM admin"],
      vocabulary: ["QBR","coverage","capacity model","quote-to-cash","lead routing"],
      goals: ["Predictable forecasts","Seller productivity","Clean data"],
      pain_points: ["Custom objects debt","Low adoption","Ad hoc asks"],
      tools: ["Salesforce","Clari","GSheets"],
      tags: ["discipline:sales","domain:operations"],
      mappings: {}
    },
    {
      id: "marketing-operations-manager",
      name: "Marketing operations manager",
      profession: "Marketing ops",
      summary: "Runs the martech stack and data flows for reliable campaigns and measurement.",
      core_tasks: ["Integrate tools","Govern data","Build automations","Report KPIs"],
      skills: ["ESP/MA platforms","APIs","SQL","Attribution"],
      vocabulary: ["lead source","MQL","UTM strategy","field mapping","privacy consent"],
      goals: ["Reliable data","Speed to launch","Compliance"],
      pain_points: ["Schema drift","Privacy changes","DIY integrations"],
      tools: ["Marketo","HubSpot","Segment"],
      tags: ["discipline:marketing","domain:operations"],
      mappings: {}
    },

    // ===== Strategy & Analysis =====
    {
      id: "business-analyst",
      name: "Business analyst",
      profession: "Analysis",
      summary: "Translates business needs into requirements and processes.",
      core_tasks: ["Elicit requirements","Document flows","Define acceptance criteria","Partner with dev/QA"],
      skills: ["Facilitation","Process mapping","Specs","Stakeholder mgmt"],
      vocabulary: ["BRD","user story","use case","as-is/to-be","acceptance criteria"],
      goals: ["Clear requirements","Reduced rework","Traceability"],
      pain_points: ["Ambiguity","Scope creep","Sign-off delays"],
      tools: ["Confluence","Miro","Jira"],
      tags: ["discipline:analysis","domain:it"],
      mappings: {}
    },

    // ===== Cloud / Security / Data Platform =====
    {
      id: "cloud-architect",
      name: "Cloud architect",
      profession: "Architecture",
      summary: "Designs cloud solutions balancing cost, reliability, and security.",
      core_tasks: ["Choose services","Design networks/IAM","Cost reviews","Resilience patterns"],
      skills: ["AWS/GCP/Azure","Networking","Security","Costing"],
      vocabulary: ["VPC","peering","autoscaling","SLA/SLO","landing zone"],
      goals: ["Reliable & secure infra","Cost efficiency","Operability"],
      pain_points: ["Legacy constraints","Quota limits","Vendor lock-in"],
      tools: ["Terraform","Cloud consoles","Grafana"],
      tags: ["discipline:architecture","domain:cloud"],
      mappings: {}
    },
    {
      id: "database-administrator",
      name: "Database administrator (DBA)",
      profession: "Data platform",
      summary: "Maintains databases for performance, reliability, and security.",
      core_tasks: ["Backups & recovery","Tuning & indexes","Access control","Patch/upgrade"],
      skills: ["SQL","Performance tuning","HA/replication","Security"],
      vocabulary: ["VACUUM","query plan","index scan","replica lag","RPO/RTO"],
      goals: ["Fast queries","Minimal downtime","Data safety"],
      pain_points: ["Hot tables","Lock contention","Late migrations"],
      tools: ["PostgreSQL/MySQL","pgAdmin","Cloud DB services"],
      tags: ["discipline:data","domain:platform"],
      mappings: {}
    },
    {
      id: "mlops-engineer",
      name: "MLOps engineer",
      profession: "Engineer",
      summary: "Builds pipelines and tooling to train, deploy, and monitor ML models.",
      core_tasks: ["Model packaging","CI/CD for ML","Feature store","Monitoring/drift"],
      skills: ["Python","Containers","Orchestration","Observability"],
      vocabulary: ["drift","feature store","model registry","A/B vs shadow","latency budget"],
      goals: ["Reliable deployment","Reproducibility","Fast rollback"],
      pain_points: ["Data skew","Infra cost","Versioning chaos"],
      tools: ["MLflow","Kubeflow","Airflow","Prometheus"],
      tags: ["discipline:data","domain:mlops"],
      mappings: {}
    },
    {
      id: "penetration-tester",
      name: "Penetration tester",
      profession: "Security",
      summary: "Emulates attackers to find exploitable weaknesses.",
      core_tasks: ["Scope & plan tests","Exploit vulns","Document findings","Retest fixes"],
      skills: ["Exploit dev","Network/app testing","Reporting","Scripting"],
      vocabulary: ["CVE","CWE","pivot","priv-esc","post-exploitation"],
      goals: ["Actionable findings","Risk reduction","Developer education"],
      pain_points: ["Scope limitations","Timeboxed testing","Mitigation delays"],
      tools: ["Burp","Nmap","Metasploit"],
      tags: ["discipline:security","domain:offense"],
      mappings: {}
    },
    {
      id: "soc-analyst",
      name: "SOC analyst",
      profession: "Security operations",
      summary: "Monitors detections and investigates incidents in real time.",
      core_tasks: ["Triage alerts","Hunt threats","Escalate incidents","Tune detections"],
      skills: ["SIEM","Forensics","Scripting","Comms"],
      vocabulary: ["IOC","TTPs","EDR","playbook","false positive"],
      goals: ["Fast detection","Low noise","Clear handoffs"],
      pain_points: ["Alert fatigue","Log gaps","Shadow IT"],
      tools: ["Splunk","Elastic","CrowdStrike"],
      tags: ["discipline:security","domain:soc"],
      mappings: {}
    },
    {
      id: "grc-analyst",
      name: "GRC analyst",
      profession: "Risk & compliance",
      summary: "Manages policies, controls, and audits across frameworks.",
      core_tasks: ["Map controls","Collect evidence","Assess risk","Support audits"],
      skills: ["Frameworks (SOC2/ISO)","Policy writing","Vendor risk","Metrics"],
      vocabulary: ["control owner","artifact","gap analysis","risk register","attestation"],
      goals: ["Clean audits","Lower risk","Process clarity"],
      pain_points: ["Evidence wrangling","Changing scope","Tool silos"],
      tools: ["Vanta","Drata","OneTrust"],
      tags: ["discipline:risk","domain:grc"],
      mappings: {}
    },
    {
      id: "incident-responder",
      name: "Incident responder",
      profession: "Security",
      summary: "Coordinates technical and communications response to security incidents.",
      core_tasks: ["Scope & contain","Eradicate & recover","Postmortems","Stakeholder updates"],
      skills: ["Forensics","Coordination","Comms","Automation"],
      vocabulary: ["IR plan","tabletop","chain of custody","IOC","CIRP"],
      goals: ["Fast MTTR","Clear comms","Learning culture"],
      pain_points: ["Incomplete logs","Unowned systems","Legal constraints"],
      tools: ["TheHive","Jira","EDR/XDR"],
      tags: ["discipline:security","domain:ir"],
      mappings: {}
    },

    // ===== Hardware / Manufacturing =====
    {
      id: "mechanical-engineer",
      name: "Mechanical engineer",
      profession: "Engineer",
      summary: "Designs mechanical components and assemblies for performance and manufacturability.",
      core_tasks: ["CAD models","Tolerance analysis","Prototype & test","DFM/DFA reviews"],
      skills: ["Statics/dynamics","Materials","CAD","GD&T"],
      vocabulary: ["FEA","GD&T","BOM","tolerance stack","DFM"],
      goals: ["Robust design","Cost-effective builds","On-time release"],
      pain_points: ["Supplier lead times","Late changes","Test failures"],
      tools: ["SolidWorks","Fusion 360","ANSYS"],
      tags: ["discipline:engineering","domain:mechanical"],
      mappings: {}
    },
    {
      id: "electrical-engineer",
      name: "Electrical engineer",
      profession: "Engineer",
      summary: "Designs circuits and PCBs, ensuring signal integrity and safety.",
      core_tasks: ["Schematic/PCB","Simulate & test","Compliance prep","Bring-up & debug"],
      skills: ["Analog/digital design","Power","EMC","Debugging"],
      vocabulary: ["schematic","impedance","EMI/EMC","decoupling","bring-up"],
      goals: ["Stable power","Noise margins","Cert passes"],
      pain_points: ["EMI surprises","Component shortages","Thermal issues"],
      tools: ["Altium","KiCad","Oscilloscopes"],
      tags: ["discipline:engineering","domain:electrical"],
      mappings: {}
    },
    {
      id: "embedded-systems-engineer",
      name: "Embedded systems engineer",
      profession: "Engineer",
      summary: "Builds firmware for constrained devices interfacing with hardware.",
      core_tasks: ["Write firmware","Integrate drivers","RTOS tasks","Debug & optimize"],
      skills: ["C/C++","RTOS","Peripherals","Low-level debug"],
      vocabulary: ["ISR","DMA","I2C/SPI/UART","bootloader","watchdog"],
      goals: ["Deterministic behavior","Low power","Reliable I/O"],
      pain_points: ["Hardware errata","Limited memory","Toolchain quirks"],
      tools: ["Segger","Logic analyzers","Compilers/IDEs"],
      tags: ["discipline:engineering","domain:embedded"],
      mappings: {}
    },
    {
      id: "industrial-designer",
      name: "Industrial designer",
      profession: "Designer",
      summary: "Designs physical products balancing ergonomics, aesthetics, and manufacturability.",
      core_tasks: ["Concept sketches","Mockups/CMF","User testing","Handoff to ME"],
      skills: ["Ergonomics","Form language","CMF","Prototyping"],
      vocabulary: ["CMF","DFM","surface finish","tolerance","parting line"],
      goals: ["Delightful form","Usable products","Feasible production"],
      pain_points: ["Cost vs form","Tooling constraints","Late changes"],
      tools: ["KeyShot","Rhino","Figma"],
      tags: ["discipline:design","domain:hardware"],
      mappings: {}
    },
    {
      id: "manufacturing-engineer",
      name: "Manufacturing engineer",
      profession: "Engineer",
      summary: "Develops processes to build products reliably at scale.",
      core_tasks: ["Line design","Work instructions","Yield analysis","Continuous improvement"],
      skills: ["Process engineering","Lean","SPC","Fixture design"],
      vocabulary: ["takt time","OEE","capability (Cp/Cpk)","first pass yield","poka-yoke"],
      goals: ["Stable yields","Lower cycle time","Safety"],
      pain_points: ["Supplier variability","Equipment downtime","Training gaps"],
      tools: ["MES","Minitab","CAD"],
      tags: ["discipline:engineering","domain:manufacturing"],
      mappings: {}
    },
    {
      id: "quality-engineer",
      name: "Quality engineer (manufacturing)",
      profession: "Quality",
      summary: "Prevents defects via inspection plans, SPC, and corrective actions.",
      core_tasks: ["Control plans","PPAP/FAI","Root cause & CAPA","Audit suppliers"],
      skills: ["SPC","FMEA","8D","Auditing"],
      vocabulary: ["PPAP","FAI","CAPA","control chart","GR&R"],
      goals: ["Low defects","Stable process","Supplier quality"],
      pain_points: ["Measurement noise","Incomplete data","Resistance to change"],
      tools: ["Minitab","QMS","Calipers/gauges"],
      tags: ["discipline:quality","domain:manufacturing"],
      mappings: {}
    },

    // ===== Supply Chain & Logistics =====
    {
      id: "supply-chain-manager",
      name: "Supply chain manager",
      profession: "Operations",
      summary: "Plans and manages sourcing, production, and distribution flows.",
      core_tasks: ["Forecast demand","Plan inventory","Manage suppliers","Monitor OTIF"],
      skills: ["S&OP","Negotiation","Analytics","Risk mgmt"],
      vocabulary: ["lead time","MOQ","safety stock","OTIF","Incoterms"],
      goals: ["On-time delivery","Healthy inventory","Cost control"],
      pain_points: ["Shortages","Forecast error","Logistics delays"],
      tools: ["ERP","APS","Spreadsheets"],
      tags: ["discipline:operations","domain:supply-chain"],
      mappings: {}
    },
    {
      id: "procurement-manager",
      name: "Procurement manager",
      profession: "Operations",
      summary: "Sources vendors and negotiates contracts for value and reliability.",
      core_tasks: ["RFPs/RFQs","Negotiate terms","Supplier scorecards","Contract mgmt"],
      skills: ["Negotiation","Cost analysis","Legal basics","Vendor mgmt"],
      vocabulary: ["MSA","SLA","TCO","lead time","LTAs"],
      goals: ["Best value","Supplier reliability","Compliance"],
      pain_points: ["Single-source risk","Price volatility","Hidden costs"],
      tools: ["ERP","eSourcing","Contract systems"],
      tags: ["discipline:operations","domain:procurement"],
      mappings: {}
    },
    {
      id: "logistics-manager",
      name: "Logistics manager",
      profession: "Operations",
      summary: "Coordinates transportation and warehousing to meet service levels.",
      core_tasks: ["Carrier selection","Route planning","Track shipments","Resolve exceptions"],
      skills: ["Routing","Carrier mgmt","Costing","Analytics"],
      vocabulary: ["LTL/FTL","bill of lading","demurrage","HS code","3PL"],
      goals: ["On-time delivery","Lower freight costs","Visibility"],
      pain_points: ["Customs delays","Capacity crunches","Damage claims"],
      tools: ["TMS","WMS","Telematics"],
      tags: ["discipline:operations","domain:logistics"],
      mappings: {}
    },
    {
      id: "warehouse-operations-manager",
      name: "Warehouse operations manager",
      profession: "Operations",
      summary: "Runs safe, efficient warehouse processes and teams.",
      core_tasks: ["Slotting & layout","Pick/pack/ship","Cycle counts","Safety training"],
      skills: ["Lean","People mgmt","Layout","Metrics"],
      vocabulary: ["SKU","cycle count","wave picking","ASN","dock door"],
      goals: ["Accuracy","Throughput","Safety"],
      pain_points: ["Seasonal spikes","Space limits","Injury risk"],
      tools: ["WMS","RF scanners","Labeling systems"],
      tags: ["discipline:operations","domain:warehouse"],
      mappings: {}
    },

    // ===== Built Environment =====
    {
      id: "civil-engineer",
      name: "Civil engineer",
      profession: "Engineer",
      summary: "Designs and oversees infrastructure projects with safety and compliance.",
      core_tasks: ["Site analysis","Structural calcs","Permitting","Construction oversight"],
      skills: ["Statics","Codes","Project mgmt","CAD"],
      vocabulary: ["grade","load path","shear/bending","EIR","RFI"],
      goals: ["Safe designs","On-budget builds","Regulatory compliance"],
      pain_points: ["Permit delays","Soil surprises","Change orders"],
      tools: ["AutoCAD","Civil 3D","STAAD"],
      tags: ["discipline:engineering","domain:civil"],
      mappings: {}
    },
    {
      id: "architect-building",
      name: "Architect (building)",
      profession: "Architecture",
      summary: "Designs buildings balancing form, function, and code.",
      core_tasks: ["Program requirements","Concept & schematics","Construction docs","CA & punchlist"],
      skills: ["Design","Codes/ADA","Coordination","Visualization"],
      vocabulary: ["schematic design","CD set","RCP","egress","setback"],
      goals: ["User comfort","Aesthetic quality","Code compliance"],
      pain_points: ["Zoning constraints","Budget vs vision","Coordination issues"],
      tools: ["Revit","Rhino","Bluebeam"],
      tags: ["discipline:architecture","domain:built"],
      mappings: {}
    },
    {
      id: "construction-project-manager",
      name: "Construction project manager",
      profession: "Construction",
      summary: "Plans and controls construction projects through schedule, budget, and quality.",
      core_tasks: ["Create schedule","Manage subs","Track costs","Risk & safety"],
      skills: ["Scheduling","Contracts","Change control","Coordination"],
      vocabulary: ["submittals","RFI","pay app","critical path","punch list"],
      goals: ["On-time delivery","Quality","Safety"],
      pain_points: ["Weather impacts","Supply delays","Scope gaps"],
      tools: ["Primavera P6","Procore","Bluebeam"],
      tags: ["discipline:construction","domain:project"],
      mappings: {}
    },

    // ===== Civic & Nonprofit =====
    {
      id: "policy-analyst",
      name: "Policy analyst",
      profession: "Public policy",
      summary: "Evaluates policies using evidence, modeling, and stakeholder impacts.",
      core_tasks: ["Literature review","Data analysis","Policy options","Recommendations"],
      skills: ["Research","Quant/qual methods","Writing","Stakeholder mapping"],
      vocabulary: ["counterfactual","cost‑benefit","equity","unintended consequences","implementation risk"],
      goals: ["Evidence‑based advice","Feasible options","Public value"],
      pain_points: ["Data gaps","Political constraints","Time pressure"],
      tools: ["Stata/R","Excel"," GIS"],
      tags: ["discipline:policy","domain:public-sector"],
      mappings: {}
    },
    {
      id: "grant-writer",
      name: "Grant writer",
      profession: "Nonprofit",
      summary: "Crafts fundable proposals aligned to program goals and grantor criteria.",
      core_tasks: ["Research opportunities","Assemble narratives & budgets","Coordinate partners","Submit & report"],
      skills: ["Storytelling","Budgeting","Compliance","Project management"],
      vocabulary: ["RFP","logic model","deliverables","indirects","evaluation plan"],
      goals: ["Funding secured","Program alignment","Compliance"],
      pain_points: ["Tight deadlines","Complex requirements","Data requests"],
      tools: ["Grants.gov","Foundation Center","Google Docs"],
      tags: ["discipline:nonprofit","domain:fundraising"],
      mappings: {}
    },

    // ===== Business Leadership & Ops (Misc) =====
    {
      id: "entrepreneur",
      name: "Entrepreneur / Founder",
      profession: "Business",
      summary: "Validates problems, builds solutions, and searches for repeatable, scalable models.",
      core_tasks: ["Customer discovery","MVP experiments","Fundraising","Hiring & GTM"],
      skills: ["Opportunity sizing","Storytelling","Prioritization","Grit"],
      vocabulary: ["runway","PMF","unit economics","churn","flywheel"],
      goals: ["Product‑market fit","Growth","Sustainable economics"],
      pain_points: ["Resource scarcity","Focus drift","Hiring"],
      tools: ["Notion","Figma","Stripe","Mixpanel"],
      tags: ["discipline:business","domain:startups","alias:founder"],
      mappings: {}
    },
    {
      id: "executive-assistant",
      name: "Executive assistant",
      profession: "Operations",
      summary: "Amplifies leaders through calendar, comms, and process excellence.",
      core_tasks: ["Calendar & travel","Briefings & docs","Meeting cadence","Follow‑through"],
      skills: ["Organization","Communication","Prioritization","Confidentiality"],
      vocabulary: ["brief","holding statements","run of show","board prep","delegation"],
      goals: ["Leader leverage","Smooth operations","Zero dropped balls"],
      pain_points: ["Last‑minute changes","Conflicting priorities","Opaque context"],
      tools: ["Google Workspace","Notion","Slack","Expensify"],
      tags: ["discipline:operations","domain:admin"],
      mappings: {}
    },

    // ===== Fun / Creative Outlier =====
    {
      id: "dungeon-master",
      name: "Dungeon Master (tabletop RPG)",
      profession: "Creative facilitator",
      summary: "Designs encounters and adjudicates rules to create memorable collaborative stories.",
      core_tasks: ["Prepare adventures","Balance encounters","Role‑play NPCs","Keep table engaged"],
      skills: ["Improvisation","World‑building","Rules knowledge","Time management"],
      vocabulary: ["initiative","homebrew","session zero","DC","narrative control"],
      goals: ["Player fun","Fair challenges","Pacing"],
      pain_points: ["Scheduling","Rules disputes","Spotlight imbalance"],
      tools: ["Roll20","Foundry VTT","D&D Beyond"],
      tags: ["discipline:games","domain:ttrpg","alias:dm"],
      mappings: {}
    }
  ];

  // Lightweight search hooks (optional; ignored by v1 UI if unused)
  PERSONAS.forEach(p => {
    p.meta = p.meta || {};
    const extras = new Set([p.name, p.profession, ...(p.meta.synonyms || []), ...(p.tags || [])]);
    p.meta.search_text = Array.from(extras).join(" ").toLowerCase();
  });

  // Export for browser and Node/CommonJS
  root.PERSONAS = PERSONAS;
  if (typeof module !== 'undefined') module.exports = PERSONAS;
})(typeof window !== 'undefined' ? window : globalThis);
